In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
pd.read_csv('Nashik_House Price.csv')

      City           Area Flat_type Parking  Area_SqMeter  Price_Lakhs
0   Nashik   Govind Nagar     1 BHK      No         57.60        27.50
1   Nashik   Govind Nagar     1 BHK     Yes         59.45        31.20
2   Nashik   Govind Nagar     2 BHK     Yes         78.96        37.40
3   Nashik   Govind Nagar     3 BHK     Yes         97.55        47.10
4   Nashik  Gangapur Road     1 BHK     Yes         59.45        25.50
5   Nashik  Gangapur Road     2 BHK     Yes         80.80        30.50
6   Nashik  Gangapur Road     3 BHK     Yes        102.20        45.70
7   Nashik    Ashok Nagar      1 RK      No         41.80        17.80
8   Nashik    Ashok Nagar     1 BHK      No         60.10        25.20
9   Nashik    Ashok Nagar     2 BHK     Yes         82.70        30.50
10    Pune         Wagoli     1 BHK      No         53.80        34.40
11    Pune         Wagoli     1 BHK     Yes         55.20        37.65
12    Pune         Wagoli     2 BHK     Yes         72.90        51.51
13    Pune         Wagoli     3 BHK     Yes         85.40        62.78
14    Pune     Wadgaon_BK     1 BHK     Yes         56.70        31.70
15    Pune     Wadgaon_BK     2 BHK     Yes         71.80        42.70
16    Pune     Wadgaon_BK     3 BHK     Yes         71.80        52.80

In [3]:
df=pd.read_csv('Nashik_House Price.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          17 non-null     object
 1   Area          17 non-null     object
 2   Flat_type     17 non-null     object
 3   Parking       17 non-null     object
 4   Area_SqMeter  17 non-null     float64
 5   Price_Lakhs   17 non-null     float64
dtypes: float64(2), object(4)
memory usage: 944.0+ bytes

In [5]:
df.isnull().sum().sum()

0

In [7]:
df.isnull().sum()

City            0
Area            0
Flat_type       0
Parking         0
Area_SqMeter    0
Price_Lakhs     0
dtype: int64

In [8]:
df.head()

     City           Area Flat_type Parking  Area_SqMeter  Price_Lakhs
0  Nashik   Govind Nagar     1 BHK      No         57.60         27.5
1  Nashik   Govind Nagar     1 BHK     Yes         59.45         31.2
2  Nashik   Govind Nagar     2 BHK     Yes         78.96         37.4
3  Nashik   Govind Nagar     3 BHK     Yes         97.55         47.1
4  Nashik  Gangapur Road     1 BHK     Yes         59.45         25.5

In [9]:
df.shape

(17, 6)

In [10]:
df.size

102

In [11]:
cat=df.select_dtypes(include='object')
cat.shape

(17, 4)

In [14]:
cat.head(2)

     City          Area Flat_type Parking
0  Nashik  Govind Nagar     1 BHK      No
1  Nashik  Govind Nagar     1 BHK     Yes

In [15]:
cat_oh=cat.drop('Flat_type',axis=1)
cat_oh.head()

     City           Area Parking
0  Nashik   Govind Nagar      No
1  Nashik   Govind Nagar     Yes
2  Nashik   Govind Nagar     Yes
3  Nashik   Govind Nagar     Yes
4  Nashik  Gangapur Road     Yes

In [17]:
cat_oh['City'].value_counts()

City
Nashik    10
Pune       7
Name: count, dtype: int64

In [23]:
for x in cat_oh.columns:
    print(x,":",len(cat_oh[x].unique()))
#we have total nine categories under the 3 nominal categories variable

City : 2
Area : 5
Parking : 2

In [24]:
#for nominal categorical variable to encode -- dummy or one hot Encoder

In [26]:
dummy_df=pd.get_dummies(cat_oh)
dummy_df.head(2)

,City_Nashik,City_Pune,Area_Ashok Nagar,Area_Gangapur Road,Area_Govind Nagar,Area_Wadgaon_BK,Area_Wagoli,Parking_No,Parking_Yes
0,True,False,False,False,True,False,False,True,False
1,True,False,False,False,True,False,False,False,True

In [27]:
dummy_df.shape

(17, 9)

In [28]:
dummy_df=dummy_df.astype(int)
dummy_df.head()

,City_Nashik,City_Pune,Area_Ashok Nagar,Area_Gangapur Road,Area_Govind Nagar,Area_Wadgaon_BK,Area_Wagoli,Parking_No,Parking_Yes
0,1,0,0,0,1,0,0,1,0
1,1,0,0,0,1,0,0,0,1
2,1,0,0,0,1,0,0,0,1
3,1,0,0,0,1,0,0,0,1
4,1,0,0,1,0,0,0,0,1

In [30]:
dummy_df.shape

(17, 9)

In [31]:
dummy_df.keys()

Index(['City_Nashik', 'City_Pune', 'Area_Ashok Nagar', 'Area_Gangapur Road',
       'Area_Govind Nagar', 'Area_Wadgaon_BK', 'Area_Wagoli', 'Parking_No',
       'Parking_Yes'],
      dtype='object')

In [35]:
from sklearn.preprocessing import OneHotEncoder
oh_enc=OneHotEncoder(sparse_output=False,)
#sparse_output =False it menans output in numpy array 
oh_enc_arr=oh_enc.fit_transform(cat_oh[['City']])
oh_enc_arr

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.],
       [0., 1.]])

In [36]:
oh_enc_arr=oh_enc.fit_transform(cat_oh)
oh_enc_arr

array([[1., 0., 0., 0., 1., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 1., 0., 0., 0., 0., 1.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 1., 0.],
       [1., 0., 1., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 0., 1., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1., 0., 0., 1.]])

In [38]:
oh_enc_arr.shape

(17, 9)

In [55]:
import numpy as np
type(oh_enc_arr)
#numpy.ndarray
dummy_df.keys()

Index(['City_Nashik', 'City_Pune', 'Area_Ashok Nagar', 'Area_Gangapur Road',
       'Area_Govind Nagar', 'Area_Wadgaon_BK', 'Area_Wagoli', 'Parking_No',
       'Parking_Yes'],
      dtype='object')

In [43]:
oh_enc=OneHotEncoder(sparse_output=False,drop='first')
oh_enc_arr=oh_enc.fit_transform(cat_oh)
oh_enc_arr

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 0., 1., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 0., 1., 1.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0., 1.],
       [1., 0., 0., 1., 0., 1.]])

In [47]:
dummy_df.keys()

Index(['City_Nashik', 'City_Pune', 'Area_Ashok Nagar', 'Area_Gangapur Road',
       'Area_Govind Nagar', 'Area_Wadgaon_BK', 'Area_Wagoli', 'Parking_No',
       'Parking_Yes'],
      dtype='object')

In [48]:
oh_enc_df=pd.DataFrame(oh_enc_arr,columns=['City_Pune','Area_Gangapur Road','Area_Govind Nagar', 'Area_Wadgaon_BK', 'Area_Wagoli', 'Parking_Yes'])
oh_enc_df.head(2)

,City_Pune,Area_Gangapur Road,Area_Govind Nagar,Area_Wadgaon_BK,Area_Wagoli,Parking_Yes
0,0.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,1.0,0.0,0.0,1.0

In [49]:
oh_enc_df.shape

(17, 6)

In [53]:
df['City']=oh_enc_df[['City_Pune']].copy()
df['City'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 17 entries, 0 to 16
Series name: City
Non-Null Count  Dtype
--------------  -----
17 non-null     float64
dtypes: float64(1)
memory usage: 264.0 bytes

In [52]:
print(df.columns)

Index(['City', 'Area', 'Flat_type', 'Parking', 'Area_SqMeter', 'Price_Lakhs'], dtype='object')

In [54]:
df['Parking']=oh_enc_df[['Parking_Yes']].copy()
df['Parking'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 17 entries, 0 to 16
Series name: Parking
Non-Null Count  Dtype
--------------  -----
17 non-null     float64
dtypes: float64(1)
memory usage: 264.0 bytes

In [56]:
df['Area']=oh_enc_df[['Area_Gangapur Road']].copy()
df['Area'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 17 entries, 0 to 16
Series name: Area
Non-Null Count  Dtype
--------------  -----
17 non-null     float64
dtypes: float64(1)
memory usage: 264.0 bytes

In [57]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   City          17 non-null     float64
 1   Area          17 non-null     float64
 2   Flat_type     17 non-null     object
 3   Parking       17 non-null     float64
 4   Area_SqMeter  17 non-null     float64
 5   Price_Lakhs   17 non-null     float64
dtypes: float64(5), object(1)
memory usage: 944.0+ bytes

In [58]:
df['Flat_type'].unique()

array(['1 BHK', '2 BHK', '3 BHK', '1 RK'], dtype=object)

In [59]:
mapping = {
    '1 RK': 0,
    '1 BHK': 1,
    '2 BHK': 2,
    '3 BHK': 3
}

df['Flat_type'] = df['Flat_type'].map(mapping)

In [60]:
df['Flat_type'].head()

0    1
1    1
2    2
3    3
4    1
Name: Flat_type, dtype: int64

In [61]:
df

    City  Area  Flat_type  Parking  Area_SqMeter  Price_Lakhs
0    0.0   0.0          1      0.0         57.60        27.50
1    0.0   0.0          1      1.0         59.45        31.20
2    0.0   0.0          2      1.0         78.96        37.40
3    0.0   0.0          3      1.0         97.55        47.10
4    0.0   1.0          1      1.0         59.45        25.50
5    0.0   1.0          2      1.0         80.80        30.50
6    0.0   1.0          3      1.0        102.20        45.70
7    0.0   0.0          0      0.0         41.80        17.80
8    0.0   0.0          1      0.0         60.10        25.20
9    0.0   0.0          2      1.0         82.70        30.50
10   1.0   0.0          1      0.0         53.80        34.40
11   1.0   0.0          1      1.0         55.20        37.65
12   1.0   0.0          2      1.0         72.90        51.51
13   1.0   0.0          3      1.0         85.40        62.78
14   1.0   0.0          1      1.0         56.70        31.70
15   1.0   0.0          2      1.0         71.80        42.70
16   1.0   0.0          3      1.0         71.80        52.80

In [71]:
# Another we used to convert ordinal data 
#df.info()

In [72]:
#df1=df.iloc[:,2:3]
#df1.head()

In [73]:
#df1['Flat_type'].value_counts()

In [74]:
#from sklearn.preprocessing import OrdinalEncoder
#oe=OrdinalEncoder(categories=[['1RK','1BHK','2BHK','3BHK']])

#df1_oe= oe.fit_transform(df1)
#df1_oe

In [77]:
#df['Flat_type'].unique()

In [76]:
#import numpy as np
#type(df1_oe)
#np.ndarray
#df1=pd.DataFrame(df1_oe,columns=['Flat_type'])
#df1.head()

In [78]:
#df.update(df1)
#df.head()