In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
pd.read_csv('50_Startups.csv')

    Unnamed: 0  R&D Spend  Administration  Marketing Spend  State     Profit
0            0  165349.30       136897.90        471784.20      2  192261.93
1            1  162597.80       151377.69        443898.63      1  191792.16
2            2  153441.61       101145.65        407934.64      0  191050.49
3            3  144372.51       118671.95        383199.72      2  182902.09
4            4  142107.44        91391.87        366168.52      0  166188.04
5            5  131877.00        99814.81        362861.46      2  156991.22
6            6  134615.56       147198.97        127716.92      1  156122.61
7            7  130298.23       145530.16        323876.78      0  155752.70
8            8  120542.62       148719.05        311613.39      2  152211.87
9            9  123334.98       108679.27        304981.72      1  149760.06
10          10  101913.18       110594.21        229161.05      0  146122.05
11          11  100672.06        91790.71        249744.65      1  144259.50
12          12   93863.85       127320.48        249839.54      0  141585.62
13          13   91992.49       135495.17        252665.03      1  134307.45
14          14  119943.34       156547.52        256513.02      0  132602.75
15          15  114523.71       122616.94        261776.33      2  129917.14
16          16   78013.21       121597.65        264346.16      1  126993.03
17          17   94657.26       145077.68        282574.41      2  125370.47
18          18   91749.26       114175.89        294919.67      0  124267.00
19          19   86419.80       153514.21             0.10      2  122776.96
20          20   76253.96       113867.40        298664.57      1  118474.13
21          21   78389.57       153773.53        299737.39      2  111313.12
22          22   73994.66       122782.85        303319.36      0  110352.35
23          23   67532.63       105751.13        304768.83      0  108734.09
24          24   77044.11        99281.44        140574.91      2  108552.14
25          25   64664.81       139553.26        137962.72      1  107404.44
26          26   75328.97       144136.08        134050.17      0  105733.64
27          27   72107.70       127864.65        353183.91      2  105008.41
28          28   66051.62       182645.66        118148.30      0  103282.48
29          29   65605.58       153032.16        107138.48      2  101004.74
30          30   61994.58       115641.38         91131.34      0   99937.69
31          31   61136.48       152702.02         88218.33      2   97483.66
32          32   63408.96       129219.71         46085.35      1   97427.94
33          33   55494.05       103057.59        214634.91      0   96779.02
34          34   46426.17       157694.02        210797.77      1   96712.90
35          35   46014.12        85047.54        205517.74      2   96479.61
36          36   28663.86       127056.31        201126.92      0   90708.29
37          37   44070.05        51283.24        197029.52      1   89949.24
38          38   20229.69        65948.03        185265.20      2   81229.16
39          39   38558.61        82982.19        174999.40      1   81005.86
40          40   28754.43       118546.15        172795.77      1   78240.01
41          41   27893.02        84710.87        164470.81      0   77798.93
42          42   23641.03        96189.73        148001.21      1   71498.59
43          43   15505.83       127382.40         35534.27      2   69759.08
44          44   22177.84       154806.24         28334.82      1   65200.43
45          45    1000.33       124153.14          1904.03      2   64926.18
46          46    1315.56       115816.31        297114.56      0   49490.85
47          47       0.10       135427.02             0.10      1   42559.83
48          48     542.15        51743.25             0.10      2   35673.51
49          49       0.10       116983.90         45173.16      1   14681.50

In [3]:
df=pd.read_csv('50_Startups.csv')

In [4]:
df = df.drop('Unnamed: 0', axis=1)

In [5]:
df

    R&D Spend  Administration  Marketing Spend  State     Profit
0   165349.30       136897.90        471784.20      2  192261.93
1   162597.80       151377.69        443898.63      1  191792.16
2   153441.61       101145.65        407934.64      0  191050.49
3   144372.51       118671.95        383199.72      2  182902.09
4   142107.44        91391.87        366168.52      0  166188.04
5   131877.00        99814.81        362861.46      2  156991.22
6   134615.56       147198.97        127716.92      1  156122.61
7   130298.23       145530.16        323876.78      0  155752.70
8   120542.62       148719.05        311613.39      2  152211.87
9   123334.98       108679.27        304981.72      1  149760.06
10  101913.18       110594.21        229161.05      0  146122.05
11  100672.06        91790.71        249744.65      1  144259.50
12   93863.85       127320.48        249839.54      0  141585.62
13   91992.49       135495.17        252665.03      1  134307.45
14  119943.34       156547.52        256513.02      0  132602.75
15  114523.71       122616.94        261776.33      2  129917.14
16   78013.21       121597.65        264346.16      1  126993.03
17   94657.26       145077.68        282574.41      2  125370.47
18   91749.26       114175.89        294919.67      0  124267.00
19   86419.80       153514.21             0.10      2  122776.96
20   76253.96       113867.40        298664.57      1  118474.13
21   78389.57       153773.53        299737.39      2  111313.12
22   73994.66       122782.85        303319.36      0  110352.35
23   67532.63       105751.13        304768.83      0  108734.09
24   77044.11        99281.44        140574.91      2  108552.14
25   64664.81       139553.26        137962.72      1  107404.44
26   75328.97       144136.08        134050.17      0  105733.64
27   72107.70       127864.65        353183.91      2  105008.41
28   66051.62       182645.66        118148.30      0  103282.48
29   65605.58       153032.16        107138.48      2  101004.74
30   61994.58       115641.38         91131.34      0   99937.69
31   61136.48       152702.02         88218.33      2   97483.66
32   63408.96       129219.71         46085.35      1   97427.94
33   55494.05       103057.59        214634.91      0   96779.02
34   46426.17       157694.02        210797.77      1   96712.90
35   46014.12        85047.54        205517.74      2   96479.61
36   28663.86       127056.31        201126.92      0   90708.29
37   44070.05        51283.24        197029.52      1   89949.24
38   20229.69        65948.03        185265.20      2   81229.16
39   38558.61        82982.19        174999.40      1   81005.86
40   28754.43       118546.15        172795.77      1   78240.01
41   27893.02        84710.87        164470.81      0   77798.93
42   23641.03        96189.73        148001.21      1   71498.59
43   15505.83       127382.40         35534.27      2   69759.08
44   22177.84       154806.24         28334.82      1   65200.43
45    1000.33       124153.14          1904.03      2   64926.18
46    1315.56       115816.31        297114.56      0   49490.85
47       0.10       135427.02             0.10      1   42559.83
48     542.15        51743.25             0.10      2   35673.51
49       0.10       116983.90         45173.16      1   14681.50

In [6]:
df.head()

   R&D Spend  Administration  Marketing Spend  State     Profit
0  165349.30       136897.90        471784.20      2  192261.93
1  162597.80       151377.69        443898.63      1  191792.16
2  153441.61       101145.65        407934.64      0  191050.49
3  144372.51       118671.95        383199.72      2  182902.09
4  142107.44        91391.87        366168.52      0  166188.04

In [7]:
df.tail()

    R&D Spend  Administration  Marketing Spend  State    Profit
45    1000.33       124153.14          1904.03      2  64926.18
46    1315.56       115816.31        297114.56      0  49490.85
47       0.10       135427.02             0.10      1  42559.83
48     542.15        51743.25             0.10      2  35673.51
49       0.10       116983.90         45173.16      1  14681.50

In [8]:
x= df.drop('Profit',axis=1) 
y=df['Profit']
print('shape of x = ',x.shape)
print('shape of y = ',y.shape)

shape of x =  (50, 4)
shape of y =  (50,)

In [9]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test= train_test_split(x,y,test_size=0.2,random_state=51)
print('shape of x_train = ',x_train.shape)
print('shape of y_train = ',y_train.shape)
print('shape of x_test = ',x_test.shape)
print('shape of y_test = ',y_test.shape)

shape of x_train =  (40, 4)
shape of y_train =  (40,)
shape of x_test =  (10, 4)
shape of y_test =  (10,)

In [10]:
# linear regression

In [11]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [12]:
lr.score(x_test , y_test)

0.966527247386125

In [13]:
x_pred=lr.predict(x_test)
print(x_pred)

[172113.92915715  54075.33945403  47825.42945834 148065.0945498
 192999.36316559 131208.92616479 103404.42655751  99391.75936224
 117843.6383875  181656.53694528]

In [14]:
lr.intercept_

54222.17435751561

In [21]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [16]:
y_pred=lr.predict(x_test)

In [17]:
y_test.values

array([166188.04,  35673.51,  42559.83, 129917.14, 192261.93, 125370.47,
       101004.74,  97483.66, 122776.96, 191050.49])

In [18]:
print("MAE",mean_absolute_error(y_test,y_pred))

MAE 7295.222253666329

In [19]:
print("MSE",mean_squared_error(y_test,y_pred))

MSE 88743301.44941589

In [32]:
from sklearn.metrics import root_mean_squared_error
print("RMSE =", root_mean_squared_error(y_test, y_pred))

RMSE = 9420.366311848808

In [45]:
#DecisionTreeRegressor
from sklearn.tree import DecisionTreeRegressor

In [35]:
regressor=DecisionTreeRegressor(criterion='squared_error')
regressor.fit(x_train,y_train)

DecisionTreeRegressor()

In [36]:
regressor.score(x_test,y_test)

0.8893015641679027

In [37]:
x_pred=lr.predict(x_test)
print(x_pred)

[172113.92915715  54075.33945403  47825.42945834 148065.0945498
 192999.36316559 131208.92616479 103404.42655751  99391.75936224
 117843.6383875  181656.53694528]

In [38]:
lr.intercept_

54222.17435751561

In [39]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

In [40]:
y_pred=lr.predict(x_test)

In [41]:
y_test.values

array([166188.04,  35673.51,  42559.83, 129917.14, 192261.93, 125370.47,
       101004.74,  97483.66, 122776.96, 191050.49])

In [42]:
print("MAE",mean_absolute_error(y_test,y_pred))

MAE 7295.222253666329

In [43]:
print("MSE",mean_squared_error(y_test,y_pred))

MSE 88743301.44941589

In [44]:
from sklearn.metrics import root_mean_squared_error
print("RMSE",root_mean_squared_error(y_test,y_pred))

RMSE 9420.366311848808

In [47]:
#KNeighborsRegressor
from sklearn.neighbors import KNeighborsRegressor

In [48]:
from sklearn.neighbors import KNeighborsRegressor

regressor = KNeighborsRegressor(n_neighbors=5)

regressor.fit(x_train, y_train)

KNeighborsRegressor()

In [49]:
regressor.score(x_test,y_test)

0.7910138221849043

In [50]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,root_mean_squared_error

In [51]:
print("MAE",mean_absolute_error(y_test,y_pred))

MAE 7295.222253666329

In [52]:
print("MSE",mean_squared_error(y_test,y_pred))

MSE 88743301.44941589

In [53]:
print("RMSE",root_mean_squared_error(y_test,y_pred))

RMSE 9420.366311848808

In [54]:
#RandomForestRegressor
from sklearn.ensemble import RandomForestRegressor

In [55]:
regressor=RandomForestRegressor(n_estimators=100,criterion='squared_error')
regressor.fit(x_train,y_train)

RandomForestRegressor()

In [63]:
regressor.score(x_test,y_test)

0.9700024661094788

In [59]:
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score,root_mean_squared_error

In [60]:
print("MAE",mean_absolute_error(y_test,y_pred))

MAE 7295.222253666329

In [61]:
print("MSE",mean_squared_error(y_test,y_pred))

MSE 88743301.44941589

In [62]:
print("RMSE",root_mean_squared_error(y_test,y_pred))

RMSE 9420.366311848808