In [1]:
import pandas as pd

In [2]:
employees=[('pravin',28,'Delhi'),
           ('satish',32,'Varanasi'),
           ('Aditya',25,'Mumbai'),
           ('Saumya',32,'Delhi'),
           ('Saumya',32,'Delhi'),
           ('Saumya',32,'Delhi'),
           ('Saumya',32,'Mumbai'),
           ('Aditya',25,'Dehradun'),
           ('sema',32,'Delhi')]

df = pd.DataFrame(employees,columns=['Name','Age','City'])
df

     Name  Age      City
0  pravin   28     Delhi
1  satish   32  Varanasi
2  Aditya   25    Mumbai
3  Saumya   32     Delhi
4  Saumya   32     Delhi
5  Saumya   32     Delhi
6  Saumya   32    Mumbai
7  Aditya   25  Dehradun
8    sema   32     Delhi

In [5]:
duplicate=df[df.duplicated()]
print("Duplicate Rows:")
duplicate

Duplicate Rows:

     Name  Age   City
4  Saumya   32  Delhi
5  Saumya   32  Delhi

In [6]:
duplicate=df[df.duplicated('Name')]
print("Duplicate Rows based on 'Name'")
duplicate

Duplicate Rows based on 'Name'

     Name  Age      City
4  Saumya   32     Delhi
5  Saumya   32     Delhi
6  Saumya   32    Mumbai
7  Aditya   25  Dehradun

In [7]:
duplicate=df[df.duplicated('City')]
print("Duplicate Rows based on 'City'")
duplicate

Duplicate Rows based on 'City'

     Name  Age    City
3  Saumya   32   Delhi
4  Saumya   32   Delhi
5  Saumya   32   Delhi
6  Saumya   32  Mumbai
8    sema   32   Delhi

In [9]:
duplicate=df[df.duplicated(['Name','Age'])]
print("Duplicate Rows based on Name and Age:")
duplicate

Duplicate Rows based on Name and Age:

     Name  Age      City
4  Saumya   32     Delhi
5  Saumya   32     Delhi
6  Saumya   32    Mumbai
7  Aditya   25  Dehradun

In [10]:
duplicate_sort=df[df.duplicated(['Name','Age'],keep=False)].sort_values('City')
print("Duplicate Rows based on Name and Age(sorted):")
duplicate_sort

Duplicate Rows based on Name and Age(sorted):

     Name  Age      City
7  Aditya   25  Dehradun
3  Saumya   32     Delhi
4  Saumya   32     Delhi
5  Saumya   32     Delhi
2  Aditya   25    Mumbai
6  Saumya   32    Mumbai